---
collections:
  - name: community.vmware
    source: https://galaxy.ansible.com
  - name: community.general
    source: https://galaxy.ansible.com
  - name: hetzner.hcloud
    source: https://galaxy.ansible.com