apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-azure:secret-reader
  labels:
    app.kubernetes.io/name: certmanager-azure
    app.kubernetes.io/tier: backend
    app.kubernetes.io/managed-by: Ops
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-azure:secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-azure:secret-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager-webhook-azure