---
# defaults file for k3s_init
k3s_selinux_policy_rpm: "https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm"
kube_config_dest: "~/.kube/config-{{ server_stack }}"

k3s_init_command: "curl -sfL https://get.k3s.io | K3S_TOKEN="
#k3s_init_cluster: "--cluster-init"
no_servicelb: false
no_traefik: false
k3s_init_noservicelb: ""
k3s_init_notraefik: ""
k3s_init_cloudprovider: ""
custom_cloudprovider: false