---
# defaults file for k3s_init
#k3s_selinux_policy_rpm: "https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm"
k3s_selinux_policy_rpm: "https://rpm.rancher.io/k3s/latest/common/centos/7/noarch/k3s-selinux-0.2-1.el7_8.noarch.rpm"

kube_config_dest: "~/.kube/config-{{ server_stack }}"
#k3s_version: "INSTALL_K3S_VERSION=v1.19.7+k3s1"
k3s_version: "INSTALL_K3S_VERSION=v1.21.3+k3s1"
k3s_init_command: "curl -sfL https://get.k3s.io | {{ k3s_version }} K3S_TOKEN="
#k3s_init_cluster: "--cluster-init"
no_servicelb: false
no_traefik: false
k3s_init_noservicelb: ""
k3s_init_notraefik: ""
k3s_init_cloudprovider: ""
custom_cloudprovider: false