---
# tasks file for k3s_init

#set facts for arguments
- name: set servicelb fact
  set_fact:
    k3s_init_noservicelb: "--disable servicelb"
  when: no_servicelb == true
- name: set traefik fact
  set_fact:
    k3s_init_notraefik: "--disable traefik"
  when: no_traefik == true
- name: set cloudprovider fact
  set_fact:
    k3s_init_cloudprovider: '--disable-cloud-controller --kubelet-arg="cloud-provider=external" --kubelet-arg="provider-id=vsphere://[master_node_id]"'
  when: custom_cloudprovider == true

#init first master
- include_tasks: init.yml
  vars:
    cluster_secret: "{{ k3s_cluster_secret }}"
    master_args: "--cluster-init  {{ k3s_init_noservicelb }} {{ k3s_init_notraefik }} {{ k3s_init_cloudprovider }}"
    agent_args: ""
  when: role == "master-clusterinit"

- include_tasks: master_facts.yml
  when: role == "master-clusterinit"

#init master 2-n
- include_tasks: init.yml
  vars:
    cluster_secret: "{{ k3s_cluster_secret }}"
    master_args: "--server https://{{ hostvars[groups['master-clusterinit'][0]]['clusterinit_ip'] }}:6443"
    agent_args: ""
  when: role == "master-member"

#init worker
- include_tasks: init.yml
  vars:
    cluster_secret: "{{ hostvars[groups['master-clusterinit'][0]]['node_token'] }} K3S_URL=https://{{ hostvars[groups['master-clusterinit'][0]]['clusterinit_ip'] }}"
    master_args: ""
    agent_args: "K3S_URL=https://{{ hostvars[groups['master-clusterinit'][0]]['clusterinit_ip'] }}:6443"
  when: role == "worker"

#curl -fL https://get.k3s.io | K3S_TOKEN="{{ k3s_cluster_secret }}" sh -s - --cluster-init --disable servicelb
#curl -fL https://get.k3s.io | K3S_TOKEN="{{ k3s_cluster_secret }}" sh -s - --server https://{{ hostvars[groups['master-clusterinit'][0]]['clusterinit_ip'] }}:6443
#curl -sfL https://get.k3s.io | K3S_TOKEN={{ hostvars[groups['master-clusterinit'][0]]['node_token'] }} K3S_URL=https://{{ hostvars[groups['master-clusterinit'][0]]['clusterinit_ip'] }}:6443 sh -s -
